#!/bin/bash
sudo ./install_war /var/tmp/wildbook-5.3.0-RELEASE.war
sudo ./install_node /var/tmp/animalus-0.1-SNAPSHOT-node.zip /opt/happywhale happywhale_web
sudo unzip -qo -d /opt/happywhale/wildbook /var/tmp/wildbook-5.3.0-RELEASE-config.zip

PAYLOAD="payload={\"channel\": \"#deploy\", \"username\": \"devhappywhale.com\", \"text\": \"I just got a new *deploy*\", \"icon_emoji\": \":computer:\"}";
curl -s -S -X POST --data-urlencode "$PAYLOAD" https://hooks.slack.com/services/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
