#!/bin/bash
mv /var/tmp/wildbook.dump /var/tmp/wildbook.dump.OLD
pg_dump -d wildbook -U shepherd -f /var/tmp/wildbook.dump

/opt/happywhale/install_war /var/tmp/wildbook-5.4.0-RELEASE.war
/opt/happywhale/install_node /var/tmp/animalus-0.1-SNAPSHOT-node.zip /opt/happywhale happywhale_web
sudo unzip -qo -d /opt/happywhale/wildbook /var/tmp/wildbook-5.4.0-RELEASE-config.zip

PAYLOAD="payload={\"channel\": \"#deploy\", \"username\": \"devhappywhale.com\", \"text\": \"I just got a new *deploy*\", \"icon_emoji\": \":computer:\"}";
curl -s -S -X POST --data-urlencode "$PAYLOAD" https://hooks.slack.com/services/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