#!/bin/bash

VENDORS="--exclude=tools --exclude=bcomponents"
classes=false
while [[ $# > 0 ]]
do
    key="$1"
    case $key in
        -v|--vendors)
        VENDORS=""
        shift
        ;;
        -C|--classes)
        classes=true
        shift
        ;;
	-w|--webapp)
    echo $2
	webapp=$2
	shift
	;;
        -c|--cust)
        cust=$2
        shift
        ;;
        *)
        # unknown option
        ;;
    esac
    shift
done

if [ -z ${webapp+x} ]; then
    webapp=wildbook
fi

cd wildbook-war
rsync -rv $VENDORS --exclude=WEB-INF --exclude=xcalendar --exclude=onlinehelp --exclude=images --exclude=software src/main/webapp/ $TOMCAT_HOME/webapps/${webapp}

if [ "$classes" = true ] ; then
    mvn compile -o
    rsync -rv target/classes/org/ $TOMCAT_HOME/webapps/${webapp}/WEB-INF/classes/org
fi

#
# Get cust resources copied over.
#
if [ ! -z ${cust+x} ]; then
    mvn compile -o -Dwildbook.cust=${cust}
    rsync -rv target/classes/ $TOMCAT_HOME/webapps/${webapp}/WEB-INF/classes
fi
