#!/bin/bash

VENDORS="--exclude=tools --exclude=bcomponents"
classes=false

while [[ $# > 0 ]]
do
    key="$1"
    case $key in
        -v|--vendors)
        VENDORS=""
        shift
        ;;
        -c|--classes)
        classes=true
        shift
        ;;
        *)
        # unknown option
        ;;
    esac
    shift
done

rsync -rv $VENDORS --exclude=WEB-INF --exclude=xcalendar --exclude=onlinehelp --exclude=images --exclude=software src/main/webapp/ $TOMCAT_HOME/webapps/wildbook

if [ "$classes" = true ] ; then
    mvn compile -o;
    rsync -rv target/classes/org/ $TOMCAT_HOME/webapps/wildbook/WEB-INF/classes/org
fi
