#!/bin/bash
#export MAVEN_OPTS=-Xmx512m
#mvn clean compile package -DskipTests -Dmaven.javadoc.skip=true -Dwildbook.cust=$1 $2

cd wildbook-core
mvn clean install -Dwildbook.cust=$1
if [ $? -ne 0 ]; then
    exit $?
fi
cd ../wildbook-http
mvn clean install
if [ $? -ne 0 ]; then
    exit $?
fi
cd ../wildbook-war
npm install
#gulp build
