#!/bin/bash

message=""
java=false
while [[ $# > 0 ]]
do
    key="$1"
    case $key in
        -m)
        shift
        message=$1
        message="__${message// /_}"
        ;;
        -j)
        java=true
        ;;
        *)
        # unknown option
        ;;
    esac
    shift
done

if [ "$java" = true ]; then
    DATE=`date +%Y_%m_%d_%H_%M_%S`
    version=V${DATE}${message}
    file=src/main/java/db/migration/$version.java
    cat config/db/flyway_java.template | sed "s/\${patchname}/$version/" > ${file}
else
    DATE=`date +%Y.%m.%d.%H.%M.%S`
    file=src/main/resources/db/migration/${DATE}${message}.sql
    touch ${file}
fi

echo ${file}


